use_case_1: &USE_CASE_1
  n_features: 2
  centers:
    - [ 1, 1 ]
    - [ -1, 0 ]

use_case_2: &USE_CASE_2
  n_features: 2
  centers:
    - [ 0, 0 ]
    - [ 1, 1 ]
    - [ 1, -1 ]
    - [ -1, 0 ]
    - [ -1, -1 ]
    - [ -1, 1 ]
    - [ 2, 2 ]

use_case_3: &USE_CASE_3
  n_features: 6
  centers:
    - [ -1, -1, 1.1, -1.4, 1, 0 ]
    - [ 1, -1.2, 1, -1, 1.4, -1 ]
    - [ -1, -1, 0.4, 1.9, 0, -1 ]
    - [ 0.1, -2, 2, -1, 1, -1.1 ]
    - [ -0.5, -2, 2, 0, 1, -1.5 ]

data:
  <<: *USE_CASE_1
  #  <<: *USE_CASE_2
  #  <<: *USE_CASE_3
  cluster_std: 0.35
  n_samples: 500
  train_ratio: 0.8
  valid_ratio: 0.1

model:
  hidden_nodes: null
  #  hidden_nodes: [ 20, 10 ]

hyper_parameters:
  epochs: 1500
  patience: 10
  learning_rate: 0.001
  batch_size: 100
  pin_memory: false
  num_workers: 0
