data:
  n_features: 2
  centers:
    - [ 1, 1 ]
    - [ 2, 2 ]
    - [ -1, -1 ]
    - [ -1, 1 ]
    - [ 1, -1 ]
    - [ 0, 0 ]
  #  n_features: 6
  #  centers:
  #    - [ 1, 1, 1, 1, 1, 1 ]
  #    - [ 1, -1, 1, -1, 1, -1 ]
  #    - [ -1, -1, 0, -1, 0, -1 ]
  #    - [ 0, -2, 2, -1, 1, -1 ]
  cluster_std: 0.35
  n_samples: 500
  train_ratio: 0.8
  valid_ratio: 0.1

model:
  hidden_nodes: null
  #  hidden_nodes: [ 20, 10 ]

hyper_parameters:
  epochs: 1500
  patience: 10
  learning_rate: 0.001
  batch_size: 100
  pin_memory: false
  num_workers: 0
