data:
  standardize_data: true
  normalize_weights: true

  subsample_ratio: 0.11
  hop: 1

  sampler:
    batch_size: 32
    num_workers: 6
    pin_memory: true

model:
  hidden_units: 64  # 32 128
  num_layers: 3

  dropout: 0.55
  max_z: 1000
  k: 45

hyper_parameters:
  epochs: 50
  patience: 20
  learning_rate: 0.0001

  batch_size: 128  # 32
  num_workers: 2
  pin_memory: false
