data:
  in_features: 128

model:
  graph:
    out_features: [ 100, 100, 100 ]
    dropout: [ 0.15, 0.15, 0.0 ]
  linear:
    out_features: [ 50, 20, 1 ]
    dropout: [ 0.05, 0.05, 0.0 ]

hyper_parameters:
  epochs: 300
  patience: 10
  learning_rate: 0.001  # 1e-3
  train_batch_size: 45000
  eval_batch_size: 65000
  num_workers: 0
  pin_memory: false
